title: Stella
logo: wheel.png
description: Introduction to Stella for CBSD 
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
show_downloads: true
